/**
@file RandomData.h
@author Song Jiang
@date April 4,2018
*/


#ifndef RANDOMDATA_H
#define RANDOMDATA_H



/** First, declare an array to save the data;
  * Second, generate the data by rand() funtion;
  * Third, Sort the data using radixsort algorithm.
  */
class RandomData{

  public:
      /// Constructor
      RandomData();
      /// Generate the time of event happenning using rand()function.
      void randomEvent();
      /// Generate the transction time of each customer using rand()function.
      void randomDuration();
      /// Find the maximum data and compute the digit of it.
      int maxDigit(int arr[], int num);
      /// Sort each digit using count sort.
      void countSort(int arr[],int num, int exp);
      /// Sort the data generated by rand funtion.
      void radixSort(int arr[], int num);
      //// Output the sorted data to the file.
      void printToFile();

  private:
      /// Declare the total number of customers.
      static const int max = 99999;
      /// Declare an array to save the time of event happenning.
      int arrStartTime[max];
      /// Declare an array to save the transction time of customer.
      int arrDuration[max];
};


#endif // RANDOMDATA_H
